In [24]:
# Python MPS decoding
#ic = decode_images_mps("rendering/results/obj_mps/rot_000", "rendering/patterns/mps/64-05")

# Python Gray decoding
#v, h, mask = decode_images_gray_python("rendering/results/00_obj/", "rendering/patterns/gray/default/", prefix="cam")

# Decoding storage/saving
#dec = np.stack([v, h, mask])
# with open("rendering/results/obj_gray/rot_fixed/decoded.npy", "wb") as fi:
#     np.save(fi, dec)
# import cv2
# fs = cv2.FileStorage("rendering/results/obj_new/rot_fixed/decoded.xml", cv2.FILE_STORAGE_WRITE)
# fs.write("v", dec[0].astype("float32"))
# fs.write("h", dec[1].astype("float32")) 
# fs.release()

# Fast gray decoding
#decode_images_gray("rendering/results/last_abc/obj_00190086_00", prefix="cam", pro=[2048, 2048])




In [ ]:
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import cv2

# Debug images for gray patterns
plt.figure(figsize = (20,10))
plt.imshow(v)#, cmap="gray")
plt.show()
plt.figure(figsize = (20,10))
plt.imshow(h)#, cmap="gray")
plt.show()
#dec = np.stack([v, h, mask])
print(dec.shape)

In [ ]:
# Debug output for mps decoding
import matplotlib.pyplot as plt

plt.figure(figsize = (20,20))
plt.imshow(IC, cmap="jet")
plt.show()
print(IC.dtype, IC.shape, IC[750, 750])

In [28]:
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import cv2
# # Debug images for gray patterns
# plt.figure(figsize = (20,10))
# plt.imshow(v)#, cmap="gray")
# plt.show()
# plt.figure(figsize = (20,10))
# plt.imshow(h)#, cmap="gray")
# plt.show()

import cv2
fs = cv2.FileStorage("rendering/decoded.xml", cv2.FILE_STORAGE_READ)
fv = fs.getNode("vertical").mat()
fh = fs.getNode("horizontal").mat()
print(fv.shape, fh.shape, fv.dtype, v.dtype)


#Comparison to decoding stage from scan3d
with open("rendering/pattern_0.txt", "r") as fi:
    lines = fi.readlines()

#pattern = np.zeros((2341, 3137))
pattern = np.zeros((2048, 2048))
#assert len(lines) == 2048

for idx, line in enumerate(lines):
    values = line.split("\t")[:-1]
    pattern[idx] = np.array(values)

pattern = np.nan_to_num(pattern, nan=-1.0)
pattern[mask] = -1.0

fv = np.nan_to_num(fv, nan=-1.0)
fv[mask] = -1.0

print(pattern, np.allclose(pattern, fv))
plt.figure(figsize = (20,10))
plt.imshow(pattern)#, cmap="gray")
plt.show()

plt.figure(figsize = (20,10))
plt.imshow(fv)#, cmap="gray")
plt.show()

plt.figure(figsize = (20,10))
plt.imshow(pattern-fv)#, cmap="gray")
plt.show()

# plt.figure(figsize = (20,10))
# plt.hist(fv.reshape(-1))
# plt.show()

# plt.figure(figsize = (20,10))
# plt.hist(pattern.reshape(-1))
# plt.show()

[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]] True


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …