In [87]:
import igl
import meshplot as mp
import numpy as np

r = np.array([[9.99985088e-01, -5.46014155e-03, -1.06692981e-04],
              [0.00000000e+00, -1.95366030e-02,  9.99809142e-01],
              [-5.46118386e-03, -9.99794233e-01, -1.95363117e-02]])
t = np.array([[-.00948749539, .07091672264, 0.86120602711, 1.0]])
t *= 1000.0
#ri = np.vstack([r, np.zeros(3)])
#transi = np.hstack([ri, -t.T])

r = np.vstack([r.T, np.zeros(3)])
trans = np.hstack([r, t.T])

#trans = np.linalg.inv(trans)
print(t)
print(np.linalg.inv(trans))

[[  -9.48749539   70.91672264  861.20602711 1000.        ]]
[[ 9.99985087e-01 -5.46014155e-03 -1.06692981e-04  9.96645389e-03]
 [-1.41542557e-13 -1.95366030e-02  9.99809143e-01 -8.59656188e-01]
 [-5.46118386e-03 -9.99794233e-01 -1.95363117e-02  8.76751067e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e-03]]


In [77]:
v_ref, f_ref = igl.read_triangle_mesh("pawn.obj")
v_rec, _ = igl.read_triangle_mesh("pawn_all.ply")

In [88]:
print(v_rec.shape)
v_rec_ss = v_rec[np.random.choice(v_rec.shape[0], 340670, replace=False), :]
print(v_rec_ss.shape)
mp.plot(v_rec_ss)

(20274164, 3)
(340670, 3)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-3.201236…

In [89]:
pad = np.ones((v_ref.shape[0], 1))
print(pad.shape, v_ref.shape)
v_ref_h = np.hstack([v_ref, np.ones((v_ref.shape[0], 1))])
v_trans = np.dot(trans, v_ref_h.T).T

print(np.min(v_trans), np.max(v_trans), np.mean(v_trans))
print(np.min(v_rec_ss), np.max(v_rec_ss), np.mean(v_rec_ss))

(340670, 1) (340670, 3)
-81.45640115674506 1000.0 463.28318010538646
-76.14405059814453 919.99609375 285.9441712220696


In [90]:
p = mp.plot(v_trans[:, :3], f_ref, return_plot=True)
p.add_points(v_rec_ss, shading={"point_size": 2.0})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-9.520128…

1

In [92]:
v_trans.shape

(340670, 4)

In [94]:
igl.write_triangle_mesh("reference.obj", v_trans[:, :3], f_ref)
igl.write_triangle_mesh("reconstructed.obj", v_rec_ss, np.array([[0, 1, 2]]))

True