In [17]:
import igl
import meshplot as mp
import numpy as np

r = np.array([[9.99985088e-01, -5.46014155e-03, -1.06692981e-04],
              [0.00000000e+00, -1.95366030e-02,  9.99809142e-01],
              [-5.46118386e-03, -9.99794233e-01, -1.95363117e-02]])
t = np.array([[-.00948749539, .07091672264, 0.86120602711, 1.0]])
t *= 1000.0
#ri = np.vstack([r, np.zeros(3)])
#transi = np.hstack([ri, -t.T])

r = np.vstack([r.T, np.zeros(3)])
trans = np.hstack([r, t.T])

trans = np.array([[ 5.98357629e+01, 1.73780698e+00, -5.15957625e+01, -1.13917137e+01],
                 [-2.11396908e-01, -7.89745329e+01, -2.90511434e+00,  3.18578817e+01],
                 [-5.16245870e+01,  2.33760665e+00, -5.97904575e+01,  8.60359595e+02],
                 [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])
trans[:3, :] = trans[:3, :] / 100
trans[:3, 3] = trans[:3, 3] / 10
#trans = trans.reshape(-1)

#trans = np.linalg.inv(trans)
print(t)
print(np.linalg.inv(trans))

[[  -9.48749539   70.91672264  861.20602711 1000.        ]]
[[ 0.95806796 -0.00338481 -0.82659367  0.72218967]
 [ 0.02782512 -1.26451082  0.03742889  0.00839931]
 [-0.82613214 -0.04651561 -0.95734255  0.81572968]
 [ 0.          0.          0.          1.        ]]


In [4]:
import os
print(os.chdir(".."))

None


In [18]:
#v_ref, f_ref = igl.read_triangle_mesh("pawn.obj")
#v_rec, _ = igl.read_triangle_mesh("pawn_all.ply")

v_ref, f_ref = igl.read_triangle_mesh("data/objects/colored/vase/vase2.obj")
v_rec, _ = igl.read_triangle_mesh("data/objects/colored/vase_group.ply")

In [19]:
print(v_rec.shape)
v_rec_ss = v_rec[np.random.choice(v_rec.shape[0], 340670, replace=False), :]
print(v_rec_ss.shape)
mp.plot(v_rec_ss)

(1999404, 3)
(340670, 3)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [24]:
pad = np.ones((v_ref.shape[0], 1))
print(pad.shape, v_ref.shape)
v_ref_h = np.hstack([v_ref, np.ones((v_ref.shape[0], 1))])
v_trans = np.dot(trans, v_ref_h.T).T

print(np.min(v_trans), np.max(v_trans), np.mean(v_trans))
print(np.min(v_rec_ss), np.max(v_rec_ss), np.mean(v_rec_ss))

(32002, 1) (32002, 3)
-52.573301623402294 49.67952304278932 -0.6677929284754143
-71.25892639160156 928.4085693359375 294.04479030286154


In [25]:
p = mp.plot(v_trans[:, :3], f_ref, return_plot=True)
p.add_points(v_rec_ss, shading={"point_size": 2.0})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

In [92]:
v_trans.shape

(340670, 4)

In [94]:
igl.write_triangle_mesh("reference.obj", v_trans[:, :3], f_ref)
igl.write_triangle_mesh("reconstructed.obj", v_rec_ss, np.array([[0, 1, 2]]))

True